[versions]
kotlin = "2.2.0"
agp = "8.11.1"
jreleaser = "1.19.0"

[libraries]

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = { id = "maven-publish" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
