[versions]
kotlin = "2.0.21"
agp = "8.11.1"

[libraries]

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

