name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: The release version. If omitted, the commit SHA will be used.
        type: string
        required: false
      deploy_maven_central:
        description: Whether to upload to Maven Central (publishing is still manual)
        type: boolean
        required: true
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Cache OpenCV SDK
        id: cache-opencv-sdk
        uses: actions/cache@v4
        with:
          path: opencv-sdk
          key: ${{ runner.os }}-opencv-${{ hashFiles('opencv-build-config.py', '.gitmodules') }}

      - name: Compile OpenCV SDK
        if: steps.cache-opencv-sdk.outputs.cache-hit != 'true'
        run: |
          python3 ./opencv-src/platforms/android/build_sdk.py \
            ./opencv-sdk ./opencv-src \
            --sdk_path $ANDROID_SDK_ROOT \
            --ndk_path $ANDROID_NDK_ROOT \
            --config ./opencv-build-config.py \
            --modules_list 'core,imgproc' \
            --no_samples_build --use_android_buildtools \
            --no_media_ndk --no-strict-dependencies

      - name: Cache .gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Build app
        run: ./gradlew assembleRelease

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: manga-vision
          path: mangavision/build/outputs/aar/mangavision-release.aar

      - name: Get Git SHA
        id: get-commit-info
        if: ${{ !inputs.version }}
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Deploy
        if: ${{ inputs.deploy_maven_central || (github.event_name == 'push' && github.ref_name == 'main') }}
        env:
          MAVEN_PUBLISH_VERSION: ${{ inputs.version || steps.get-commit-info.short_sha }}
          JRELEASER_GITHUB_TOKEN: ${{ github.token }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.MAVEN_CENTRAL_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.MAVEN_CENTRAL_GPG_SECRET_KEY }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: |
          ./gradlew publish
          ./gradlew jreleaserConfig
          ./gradlew jreleaserDeploy \
            ${{ (inputs.deploy_dry_run && '"-Djreleaser.dry.run=true"') || '' }}
